name: flint
favicon: null
layout_spectrum: 0.32198710017837584
typography_spectrum: 0.4664785270579159
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6588120243977755
  lightness: 0.2602046490646899
  saturation: 0.4587125079706311
  rhythmicContrast: 0.6077864421531558
purpose: []
